version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Psqlitsmesahil@123
      POSTGRES_DB: Mini_Jira
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Psqlitsmesahil@123
      POSTGRES_DB: Mini_Jira
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontendapp:
    build: ../frontend/.
    ports:
      - "8080:8080"
    volumes:
      - ../frontend/.:/app
      - /app/node_modules
    image: frontendapp
    command: [ "yarn", "start" ]
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BASE_URL=http://localhost:8000

networks:
  default:
    name: Mini_Jira

volumes:
  db_data:
